
services:
  mysql:
    image: mysql:8
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: rootkey
      MYSQL_DATABASE: localdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user_key
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: